### ISSUE TITLE
 ctorParameters.map is not a function

### ISSUE THREAD

**Issue by TkachVova** [PillowPillow/ng2-webstorage#28]
I am using Angular 2.1.2 and getting error like "Uncaught TypeError: ctorParameters.map is not a function
![capture1](https://cloud.githubusercontent.com/assets/7613489/21569777/a1f30f2c-cec8-11e6-9dbe-11e04495b1fb.PNG)
"

**Comment by AndriiDidkivsky** [comment]
Have same issue

**Comment by PillowPillow** [comment]
Hi, thanks to update your angular version to the v2.2.X at least or downgrade the library to the v1.4.2.
This issue come from the new angular-compile version

**Comment by TkachVova** [comment]
Thanks, I have updated Angular to highest version and everything is OK now.

**Comment by azanebrain** [comment]
If upgrading your version of Angular is out of the question, I've found that this issue is caused by any number of packages expecting the version of Angular Core to be different than what is actually installed.

I was able to figure out the cause of this issue by looking at the error report from ng build:

`npm WARN @angular/platform-server@2.4.4 requires a peer of @angular/core@2.4.4 but none was installed.`

This helped me realize that one of my packages expected Angular to be at v2.4.4, but I'm using v2.0.1. I updated my package.json to have both packages set to my core version like this:

`"dependencies": {
    "@angular/core": "2.0.1",
    "@angular/platform-server": "2.0.1",
}`

Your issue might not be with @angular/platform-server, but I hope this helps debug it
