### ISSUE TITLE
does this library has support for browsers that doesn't have local storage?

### ISSUE THREAD

**Issue by esakal** [PillowPillow/ng2-webstorage#8]
Hi,
Does this library has a fallback strategy to in-memory if the browser doesn't support local storage?

Thanks,
Eran.

**Comment by PillowPillow** [comment]
Hi, currently there is no fallback because of the compatibility of the local and session storage.
https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage

It works since IE8 and angular2 doesn't supports the <IE8 browsers

**Comment by emanuelet** [comment]
unfortunately that seems to cause an exception on Safari in Private mode

**Comment by PillowPillow** [comment]
Only in private mode?? It's weird. I'll try that and come back to you soon.

**Comment by awexfwex** [comment]
It gives a quota exceeded message. This is a Safari feature on both iOS and desktop when in private browsing mode. 
Fallback strategy for this is essential.

**Comment by PillowPillow** [comment]
I experienced some issues too but the last version should resolves your problems. my apologies for the delay.

**Comment by PillowPillow** [comment]
Hi, since the v1.2.3 the library has a fallback for browsers that doesn't have local storage including safari in private mode.

**Comment by dgadelha** [comment]
I'm sorry for reviving an old issue, but I'm experiencing the same problem on Edge/Chrome, where after disabling cookies (<img width="1290" alt="Image" src="https://github.com/user-attachments/assets/54281b10-07d4-4d10-acb7-d20c32aea60a" />), the lib would crash with:

```
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

when using:

```ts
provideNgxWebstorage(
  withNgxWebstorageConfig({ prefix: "pws", separator: ":" }),
  withLocalStorage()
),
```

Which was happening for some users in my open-source project (<img width="856" alt="Image" src="https://github.com/user-attachments/assets/f2ed2c28-b57c-43f5-a218-16edef501107" />) and I had to investigate a deep further.

Also, I wasn't able to use just:

```ts
provideNgxWebstorage(withNgxWebstorageConfig({ prefix: "pws", separator: ":" })),
```

nor

```ts
provideNgxWebstorage(),
```

because it'd fail with this error:

```
main.ts:31  NullInjectorError: NullInjectorError: No provider for LocalStorageService!
    at NullInjector.get (core.mjs:1600:21)
    at R3Injector.get (core.mjs:2130:27)
    at R3Injector.get (core.mjs:2130:27)
    at injectInjectorOnly (core.mjs:1111:28)
    at ɵɵinject (core.mjs:1117:40)
    at inject (core.mjs:1202:10)
    at new _ThemeService (theme.service.ts:12:29)
    at Object.ThemeService_Factory [as factory] (theme.service.ts:33:3)
```

So I had to do a workaround like this https://github.com/dgadelha/Portugol-Webstudio/commit/73a0f599cd2aa78bdbf578fa5ec5ace7f1931ded

Am I missing something? Thank you!
