### ISSUE TITLE
why must cached the data ?  

### ISSUE THREAD

**Issue by lopn** [PillowPillow/ng2-webstorage#81]
https://github.com/PillowPillow/ng2-webstorage/blob/81f4d25c997bb898473aacb28ad7b1e03b6ef41f/lib/helpers/webStorage.ts#L15

why must cached the data ? that may be effect my  program performance  ? 

can you provide the option flag to open or closed the cache ?

**Comment by PillowPillow** [comment]
Hi, 
Access the storages each time you need to retrieve a value has a perfomance cost, especially when you're binding a variable to an angular component (the angular's check will trigger the accessors multiple times and will slow down the whole application). There is no point to disable the cache since he refresh each time the storage trigger an update event (from the current tab or another).

**Comment by PillowPillow** [comment]
no event since 10 days, i close this issue. Feel free to open another if you have an other question.
